style: "github"
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/tami5/sqlite.lua
options:
  refs:
    actions:
      - closes
  commits:
    filters:
      Type:
        - sparkles
        - bug
        - zap
        - recycle
        - art
        - package
        - white_check_mark
        - lock
        - construction_worker
        - boom
  commit_groups:
    title_maps:
      sparkles: ":sparkles: Features"
      boom: ":boom: Breaking Changes"
      bug: ":bug: Bug Fixes"
      zap: ":zap: Performance Improvements"
      recycle: ":recycle: Code Refactoring"
      art: ":art: Structure/Formating"
      memo: ":memo: Add or update documentation."
      white_check_mark: ":white_check_mark: Add/Update Test Cases"
      package: ":package: Dependencies"
      lock: ":lock: Security"
      construction_worker: ":construction_worker: CI Updates"
  header:
    pattern: "^:(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE

